{{- if .Values.registrationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qpoint.fullname" . }}-token
  labels: {{- include "qpoint.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.registrationToken | b64enc }}
{{- end }}
