apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-qtap-operator.fullname" . }}-default-pod-annotations-configmap
  labels:
  {{- include "kubernetes-qtap-operator.labels" . | nindent 4 }}
data:
  annotations.yaml: {{ .Values.defaultPodAnnotationsConfigmap.annotationsYaml | toYaml
    | indent 1 }}