apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qtap.fullname" . }}
  labels:
    {{- include "qtap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "qtap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qtap.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qtap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          env:
            - name: ENDPOINT
              value: "{{ .Values.endpoint }}"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token
            - name: INGRESS_HTTP_LISTEN
              value: "{{ .Values.service.ingress.http.addr }}:{{ .Values.service.ingress.http.port }}"
            - name: INGRESS_HTTPS_LISTEN
              value: "{{ .Values.service.ingress.https.addr }}:{{ .Values.service.ingress.https.port }}"
            - name: EGRESS_HTTP_LISTEN
              value: "{{ .Values.service.egress.http.addr }}:{{ .Values.service.egress.http.port }}"
            - name: EGRESS_HTTPS_LISTEN
              value: "{{ .Values.service.egress.https.addr }}:{{ .Values.service.egress.https.port }}"
            - name: STATUS_LISTEN
              value: "{{ .Values.status.addr }}:{{ .Values.status.port }}"
            - name: COLLECTOR_LISTEN
              value: "{{ .Values.collector.addr }}:{{ .Values.collector.port }}"
          ports:
            - name: i-http-service
              containerPort: {{ .Values.service.ingress.http.port }}
              protocol: TCP
            - name: i-https-service
              containerPort: {{ .Values.service.ingress.https.port }}
              protocol: TCP
            - name: e-http-service
              containerPort: {{ .Values.service.egress.http.port }}
              protocol: TCP
            - name: e-https-service
              containerPort: {{ .Values.service.egress.https.port }}
              protocol: TCP
            - name: status
              containerPort: {{ .Values.status.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /readyz
              port: status
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: status
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: status
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
