apiVersion: v1
kind: Service
metadata:
  name: {{ include "qtap.fullname" . }}
  labels: {{- include "qtap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.egressHttpPort }}
      targetPort: e-http-service
      protocol: TCP
      name: e-http-service
    - port: {{ .Values.service.egressHttpsPort }}
      targetPort: e-https-service
      protocol: TCP
      name: e-https-service
  selector: {{- include "qtap.selectorLabels" . | nindent 4 }}
