apiVersion: v1
kind: Service
metadata:
  name: {{ include "qtap.fullname" . }}
  labels: {{- include "qtap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tcpPort }}
      targetPort: tcpService
      protocol: TCP
      name: tcpService
    - port: {{ .Values.service.httpPort }}
      targetPort: httpService
      protocol: TCP
      name: httpService
    - port: {{ .Values.service.httpsPort }}
      targetPort: httpsService
      protocol: TCP
      name: httpsService
  selector: {{- include "qtap.selectorLabels" . | nindent 4 }}
