apiVersion: v1
kind: Service
metadata:
  name: {{ include "qtap.fullname" . }}
  labels: {{- include "qtap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tcpPort }}
      targetPort: tcp-service
      protocol: TCP
      name: tcp-service
    - port: {{ .Values.service.httpPort }}
      targetPort: http-service
      protocol: TCP
      name: http-service
    - port: {{ .Values.service.httpsPort }}
      targetPort: https-service
      protocol: TCP
      name: https-service
  selector: {{- include "qtap.selectorLabels" . | nindent 4 }}
