apiVersion: v1
kind: Service
metadata:
  name: {{ include "qtap.fullname" . }}
  labels: {{- include "qtap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ingress.http.port }}
      targetPort: i-http-service
      protocol: TCP
      name: i-http-service
    - port: {{ .Values.service.ingress.https.port }}
      targetPort: i-https-service
      protocol: TCP
      name: i-https-service
    - port: {{ .Values.service.egress.http.port }}
      targetPort: e-http-service
      protocol: TCP
      name: e-http-service
    - port: {{ .Values.service.egress.https.port }}
      targetPort: e-https-service
      protocol: TCP
      name: e-https-service
  selector: {{- include "qtap.selectorLabels" . | nindent 4 }}
