apiVersion: v1
kind: Service
metadata:
  name: {{ include "qtap.fullname" . }}
  labels: {{- include "qtap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: service
      protocol: TCP
      name: service
  selector: {{- include "qtap.selectorLabels" . | nindent 4 }}
