apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qtap-operator.fullname" . }}-inject-pod-annotations-configmap
  labels:
  {{- include "qtap-operator.labels" . | nindent 4 }}
data:
  annotations.yaml: {{ .Values.injectPodAnnotationsConfigmap.annotationsYaml | toYaml
    | indent 1 }}
