apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qtap-operator.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qtap-operator
    app.kubernetes.io/part-of: qtap-operator
  {{- include "qtap-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qtap-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qtap-operator
    app.kubernetes.io/part-of: qtap-operator
  {{- include "qtap-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "qtap-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "qtap-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
