apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "qtap-operator.fullname" . }}-manager-clusterrolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qtap-operator
    app.kubernetes.io/part-of: qtap-operator
  {{- include "qtap-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "qtap-operator.fullname" . }}-manager-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "qtap-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
