apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qpoint.fullname" . }}-config
  labels: {{- include "qpoint.labels" . | nindent 4 }}
data:
  proxy-config.yaml: |
    {{- .Values.config | nindent 4 }}
