controllerManager:
  kubeRbacProxy:
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.15.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      endpoint: https://api.qpoint.io
    image:
      repository: us-docker.pkg.dev/qpoint-edge/public/kubernetes-qtap-operator
      tag: latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
injectPodAnnotationsConfigmap:
  annotationsYaml: |-
    qpoint.io/inject-ca: "true"
    qpoint.io/egress-init-tag: "v0.0.7"
    qpoint.io/qtap-tag: "v0.0.10"
    qpoint.io/egress-port-mapping: "10080:80,10443:443,10000:"
    qpoint.io/egress-accept-uids: "1010"
    qpoint.io/egress-accept-gids: "1010"
    qpoint.io/log-level: "info"
    qpoint.io/block-unknown: "false"
    qpoint.io/dns-lookup-family: "V4_ONLY"
    qpoint.io/qtap-uid: "1010"
    qpoint.io/qtap-gid: "1010"
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
servicePodAnnotationsConfigmap:
  annotationsYaml: |-
    qpoint.io/inject-ca: "true"
    qpoint.io/egress-init-tag: "v0.0.7"
    qpoint.io/egress-to-domain: "qtap-gateway.qpoint.svc.cluster.local"
    qpoint.io/egress-port-mapping: "10080:80,10443:443"
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP

# API token
token: ""
