apiVersion: v2
name: kubernetes-qtap-operator
description: A Helm chart for a Kubernetes Qtap operator
type: application
version: 0.0.1
# This is the semantic version of https://github.com/qpoint-io/kubernetes-qtap-operator/releases being deployed
appVersion: "0.0.1"
